name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]*'
  pull_request:

concurrency:
  group: >
    ${{ github.workflow }} @
    ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v3
      - name: Check out cibuildwheel (needed for tests)
        uses: actions/checkout@v3
        with:
          repository: pypa/cibuildwheel
          path: cibuildwheel
      - name: Install dependencies
        run: |
          cd cibuildwheel; python -m pip install ".[test]"
      - name: Generate a sample project
        run: |
          cd cibuildwheel; python -m test.test_projects test.test_0_basic.basic_project sample_proj
      - name: Run a sample build (GitHub Action)
        uses: pypa/cibuildwheel@v2.13.1
        with:
          package-dir: cibuildwheel/sample_proj
          output-dir: wheelhouse
